stateDiagram-v2
  direction LR
  [*] --> 正常停止
  正常停止 --> 沸騰: 蓋閉じる|ボタン
  正常停止 --> 異常停止: 障害
  沸騰 --> 保温: 100°Cで3分
  沸騰 --> 正常停止: 蓋開ける
  沸騰 --> 異常停止: 障害
  保温 --> 沸騰: ボタン
  保温 --> 正常停止: 蓋開ける
  保温 --> 異常停止: 障害
  異常停止 --> 正常停止: 復旧
